### ISSUE TITLE
Disconnected piece by Quarriers Village

### ISSUE THREAD

**Issue by dabreegster** [nptscot/corenet#24] opened 2024-12-14 16:27 UTC
![image](https://github.com/user-attachments/assets/0ad6c111-6fae-41c4-8a68-b43ca4837cdf)
https://www.openstreetmap.org/way/160738147#map=14/55.87381/-4.60859 shows up as a local access route in https://github.com/nptscot/outputdata/releases/download/v2024-12-01/combined_CN_4_2024-12-01_OS.pmtiles. It does look like a useful part of a network, but it's not connected to the rest of the CN. Intentional?

**Comment by Robinlovelace** [comment] 2024-12-14 17:56
Heads-up @wangzhao0217, any ideas of the cause?

**Comment by wangzhao0217** [comment] 2024-12-16 11:51
> d to the rest of the CN. Intentional?

Hi Dustin,
Thanks for spotting this issue. The route is disconnected because it is too far from the core network. At the moment, I only join routes to the core network if they are within a 3,000-meter range. Will take a look to address this

**Comment by Robinlovelace** [comment] 2024-12-18 10:11
Just updated this file:

```
combined_CN_4_2024-12-01_OS.pmtiles
```

**Comment by Robinlovelace** [comment] 2024-12-18 10:12
Fixed in outputdata and online:

![image](https://github.com/user-attachments/assets/de43c1bb-cb2d-476c-8d3d-1aed51b5ac53)

**Closed by Robinlovelace** 2024-12-18 10:12 UTC
